- name: Install nginx
  apt: name=nginx state=latest

- name: Insert Index Page
  template:
    src: index.html
    dest: /var/www/html/index.html

- name: Start nginx
  service: 
    name: nginx
    state: started